apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: e2e-dotnet
    appstudio.openshift.io/component: devfile-sample-dotnet60-basic-nzr8
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: devfile-sample-dotnet60-basic-nzr8
  namespace: e2e-demos-lzoz-tenant
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_devfile-samples_devfile-sample-dotnet60-basic
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/devfile-samples/devfile-sample-dotnet60-basic
